openapi: 3.0.3
info:
  title: Currency Conversion API
  description: API for converting currencies and retrieving exchange rates.
  version: 2.0.0
servers:
  - description : Production
    url: 'https://yourcurrencyconverter-api.cz'
tags:
  - name: Calculation Service
    description: Calculation of the amount based on currencies
  - name: Cache Service
    description: Operations about cache (Read / Write)
paths:
  /calculation:
    post:
      tags:
        - Calculation Service
      summary: Convert amount
      description: Convert the amount give to the currency asked
      operationId: postConvertAmount
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ConversionQuery'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversionResult'
            application/xml:
              schema:
                $ref: '#/components/schemas/ConversionResult'
        default:
          description: successful operation
  /exchange-rate-cache:
    get:
      tags:
        - Cache Service
      summary: Get exchange rate
      description: Retrieves the exchange rate compare to EUR for the currency ask from the cache
      operationId: getExchangeRate
      parameters:
        - name: from
          in: query
          description: Currency code to convert from
          required: true
          schema:
            type: string
            example: USD
      responses:
        '200':
          description: Successful retrieval
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeRate'
        '400':
          description: Invalid input
        '404':
          description: Currency not found
  /cache:
    post:
      tags:
        - Cache Service
      summary: Write exchange rates
      description: Write all the exchange rates of all available currencies
      operationId: postAllCurrencies
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ArrayExchangeRate'
      responses:
        '200':
          description: Successful operation
        default:
          description: successful operation
components:
  schemas:
    ConversionResult:
      type: object
      properties:
        from:
          type: string
          example: USD
        to:
          type: string
          example: EUR
        amount:
          type: number
          example: 100.0
        convertedAmount:
          type: number
          example: 85.0
        exchangeRate:
          type: number
          example: 0.85
    ConversionQuery:
      type: object
      properties:
        from:
          type: string
          example: USD
        to:
          type: string
          example: EUR
        amount:
          type: number
          example: 100.0
    ExchangeRate:
      type: object
      properties:
        from:
          type: string
          example: USD
        to:
          type: string
          example: EUR
        rate:
          type: number
          example: 0.85
    ArrayExchangeRate:
      type: object
      properties:
          from:
            type: string
            example: USD
          to:
            type: string
            example: EUR
          rate:
            type: number
            example: 0.85
